manifest:
  defaults:
    remote: urob

  remotes:
    - name: urob
      url-base: https://github.com/urob
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: badjeff
      url-base: https://github.com/badjeff
    - name: englmaxi
      url-base: https://github.com/englmaxi

  projects:
    - name: zmk
      remote: zmkfirmware
      import: app/west.yml
      revision: v0.2

    # ZMK modules
    - name: zmk-auto-layer
      path: modules/zmk/auto-layer
      revision: v0.2
    - name: zmk-helpers
      path: modules/zmk/helpers
      revision: v0.2
    - name: zmk-tri-state
      path: modules/zmk/tri-state
      revision: v0.2

    - name: zmk-pmw3610-driver
      remote: badjeff
      revision: main
    - name: zmk-dongle-display
      remote: englmaxi
      revision: main

    # Temporarily overload Zephyr until
    # https://github.com/zmkfirmware/zephyr/pull/40 is merged.
    - name: zephyr
      revision: v3.5.0+zmk-fixes
      clone-depth: 1
      import:
        # Only enable most commonly used boards. For less common hardware one
        # may need to enable additional modules.
        name-allowlist:
          - cmsis
          - hal_nordic
          - hal_rpi_pico
          - hal_stm32
          - lvgl
          - tinycrypt
          - pixart_pmw3610

  self:
    path: config
